worker:
  replicas: 2
  resources:
    limits:
      cpu: 2
      memory: 1G
    requests:
      cpu: 2
      memory: 1G
  env:
    #- name: EXTRA_CONDA_PACKAGES
    #  value: xgboost -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: xgboost dask-ml sklearn --upgrade
scheduler:
  env:
    #- name: EXTRA_CONDA_PACKAGES
    #  value: xgboost -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: xgboost dask-ml sklearn --upgrade
# We want to keep the same packages on the worker and jupyter environments
jupyter:
  enabled: true
  env:
    #- name: EXTRA_CONDA_PACKAGES
    #  value: numba xarray matplotlib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: xgboost dask-ml sklearn --upgrade